#!/bin/busybox ash
###############################################################################
# install-ubuntu                                                              #
#                                                                             #
# RC Script to Install Ubuntu for Laptop Rehab Project                        #
#                                                                             #
#                                                                             #
#   Authors: Wolfgang Richter <wolf@cs.cmu.edu>                               #
#                                                                             #
#   Copyright 2014 Laptop Rehab Project                                       #
#                                                                             #
# Permission is hereby granted, free of charge, to any person obtaining a     #
# copy of this software and associated documentation files (the "Software"),  #
# to deal in the Software without restriction, including without limitation   #
# the rights to use, copy, modify, merge, publish, distribute, sublicense,    #
# and/or sell copies of the Software, and to permit persons to whom the       #
# Software is furnished to do so, subject to the following conditions:        #
#                                                                             #
#     The above copyright notice and this permission notice shall be included #
#     in all copies or substantial portions of the Software.                  #
#                                                                             #
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS #
#     OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF              #
#     MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  #
#     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY    #
#     CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,    #
#     TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE       #
#     SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                  #
#                                                                             #
###############################################################################

. /etc/init.d/tc-functions

export PATH=/usr/local/sbin:/usr/local/bin:"$PATH"

usbmount() {
    USBDEVICE="$(blkid -L 'CMU Laptop Rehab 32-bit' | grep sd[^0-9]* -o)"
    USBPART="$(blkid -L 'CMU Laptop Rehab 32-bit')"
    echo "${WHITE}Found USB partition at: ${BLUE}${USBPART}.${NORMAL}"
    if [ ! -e /mnt/$(basename ${USBPART}) ]; then
        mkdir -p /mnt/$(basename ${USBPART})
    fi
    mount "${USBPART}" /mnt/$(basename ${USBPART})

    USBMOUNT="/mnt/$(basename ${USBPART})"
    echo "${WHITE}USB partition should be mounted at: ${BLUE}${USBMOUNT}.${NORMAL}"
}

findhdd() {
    HDD="$(lsblk -o NAME -e 1,2,11 -b -n -d | grep -v ${USBDEVICE} | head -n 1)"
    echo "${WHITE}Target HDD: ${BLUE}/dev/${HDD}.${NORMAL}"
}

copyubuntu() {
    echo "${WHITE}Decompressing OS image to HDD."
    gunzip -c "${USBMOUNT}/Ubuntu32.img.gz" | pv -s 6656m -p -t -e -r -B 512k > "/dev/${HDD}"
    sync
}

fixswap() {
    echo "${WHITE}Creating swap space.${NORMAL}"
    mkswap "/dev/${HDD}1"
}

resizepart() {
    echo "${WHITE}Resizing partition.${NORMAL}"
    echo ",+" | sfdisk --force -N2 "/dev/${HDD}"
    echo ",+" | sfdisk --force -N5 "/dev/${HDD}"
    echo "${WHITE}Resizing file system.${NORMAL}"
    sync
    partx -u "/dev/${HDD}"
    e2fsck -f "/dev/${HDD}5"
    sync
    resize2fs "/dev/${HDD}5"
    sync
}

waitfstab() {
    if [ -e /var/run/rebuildfstab.pid ]; then
        wait "$(cat /var/run/rebuildfstab.pid)"
    fi
}

waitfstab
echo "${GREEN}Installing Ubuntu OS${NORMAL}"

usbmount
findhdd
echo "${YELLOW}Please wait, this could take 10-15 minutes!${NORMAL}"
copyubuntu
read junk
resizepart
fixswap

echo "${GREEN}Finished installing OS.${NORMAL}"

echo "${RED}Press ANY KEY to REBOOT.${NORMAL}"
read junk
reboot
